data:
  augmentation: null
  transform: imagenet
  batch_size: 128
  dataset: Fashion MNIST
logger:
  entity: atticux
  project: pytorch-lightning-uv
  run_name: Efficientnet_V2_Fashion_MNIST_finetune-1
model:
  activation: relu
  dropout: 0.2
  efficient_version: s
  name: Efficientnet_V2
optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 6
  precision: null
